In [2]:
from bs4 import BeautifulSoup

In [3]:
import pandas as pd
import re

In [4]:
with open("movies_html.html", "r", encoding="utf-8") as f:
    html = f.read()

soup = BeautifulSoup(html, "lxml")

In [5]:
title = soup.find("h1").text
print(title)

 Demon Slayer: Kimetsu no Yaiba Infinity Castle (2025)

In [ ]:
try:
        genre_label = soup.find(string="Genres")

        if genre_label:
            genre_container = genre_label.find_next("div", class_="poster-detail-infos__value")
            genre = genre_container.find("span").text.strip()
        else:
            genre = None

    except:
        genre = None 
    genre = genre.split(",")[0] if genre else None #keep first genre only

In [8]:
movies = html.split("<!-- MOVIE")

urls=[]
titles = []
years = []
imdb_ratings = []
imdb_reviews_list = []
runtime_list = []
directors_list = []
country_list = []
genres_list = []
main_actors = []



for movie_html in movies[1:]:

    soup = BeautifulSoup(movie_html, "html.parser")
    
    try:
        title = soup.find("h1").text.strip().split("(")[0].strip()
    except:
        title = None
    
    try: 
        year = soup.find('span',class_='release-year').text.strip().replace("(", "").replace(")", "")
    except:
        year = None

    try:
        imdb_tag = soup.find('span', class_="imdb-score")
        imdb_text = imdb_tag.text.strip()

        imdb_rating = imdb_text.split()[0]
        imdb_review_count = imdb_text.split()[1].replace("(", "").replace(")", "")

    except:
        imdb_rating = None
        imdb_review_count = None

    try:
        items = soup.find_all('div', class_='title-detail-hero-details__item')
    
        runtime = None

        for item in items:
            text = item.text.strip()
        
            if 'min' in text:   # runtime always contains 'min'
               runtime = text
               break

    except:
         runtime = None

    # extract URL safely
    try:
        url_line = movie_html.split("<!-- URL: ")[1].split("-->")[0].strip()
    except:
        url_line = None 
    
    try:
        director = soup.find('span', class_='title-credit-name').text.strip()
    
    except:
        director = None

    try:
        country_label = soup.find(string="Production country")

        if country_label:
            country_text = country_label.find_next("div", class_="poster-detail-infos__value").text.strip()

            primary_country = country_text.split(",")[0].strip()
        else:
            primary_country = None

    except:
        primary_country = None

    try:
        genre_label = soup.find(string="Genres")

        if genre_label:
            genre_container = genre_label.find_next("div", class_="poster-detail-infos__value")
            genre = genre_container.find("span").text.strip()
        else:
            genre = None

    except:
        genre = None 
    genre = genre.split(",")[0] if genre else None #keep first genre only  

    try:
        actor_tags = soup.find_all("span", class_="title-credit-name")

        if actor_tags and len(actor_tags) > 1:
            main_actor = actor_tags[1].text.strip()   # first actor
        else:
            main_actor = None

    except:
        main_actor = None

    runtime_list.append(runtime)
    imdb_ratings.append(imdb_rating)
    imdb_reviews_list.append(imdb_review_count)
    titles.append(title)
    years.append(year)
    urls.append(url_line)
    directors_list.append(director)
    country_list.append(primary_country)
    genres_list.append(genre)
    main_actors.append(main_actor)
   
    
    
print(titles, years, imdb_ratings, imdb_reviews_list,runtime_list,urls,directors_list,country_list,genres_list,main_actors)

['Demon Slayer: Kimetsu no Yaiba Infinity Castle', 'One Battle After Another', 'Marty Supreme', 'Zootopia 2', 'Ne Zha 2', 'Sinners', 'Assi', '28 Years Later: The Bone Temple', 'Weapons', 'Sentimental Value', 'Geetha Govindam', 'The Secret Agent', 'Tu Yaa Main', 'Send Help', 'No Other Choice', 'Sabar Bonda', 'The Handmaiden', 'Raazi', 'Train Dreams', 'The Nice Guys', 'Eternal Sunshine of the Spotless Mind', 'Memento', 'The Gangster, the Cop, the Devil', 'To Kill a Mockingbird', 'Bāhubali: The Epic', 'Memories of Murder', 'Sirât', "Rosemary's Baby", 'The Wild Robot', 'The Silence of the Lambs', 'Like Stars on Earth', 'The Godfather', 'Zootopia', 'Argo', 'Metropolis', 'Spider-Man: No Way Home', 'The Lord of the Rings: The Fellowship of the Ring', 'Wake Up Dead Man: A Knives Out Mystery', 'The Truman Show', 'Gangubai Kathiawadi', 'The Lighthouse', 'Good Will Hunting', '50/50', 'RRR', 'Veer-Zaara', 'Inside Job', 'Homebound', 'Dum Laga Ke Haisha', 'Hi Nanna', 'La La Land', 'Man on the Run', 'Rang De Basanti', 'Queen of Hearts', 'No Country for Old Men', 'Zodiac', 'Sicario', '96', 'Dune: Part Two', 'Get Out', 'Before Sunrise', 'GoodFellas', '12th Fail', 'Top Gun: Maverick', 'Spider-Man: Homecoming', 'The Departed', 'The Man from Earth', 'The Lunchbox', 'Everything Everywhere All at Once', 'Insomnia', 'Chainsaw Man - The Movie: Reze Arc', 'Detour', 'It Was Just an Accident', 'Whiplash', 'Anora', 'There Will Be Blood', 'Incendies', 'Perfect Days', 'Andhadhun', 'The Dark Knight', 'Girls Will Be Girls', 'Hereditary', 'Spider-Man: Across the Spider-Verse', 'Bāhubali: The Beginning', 'Jujutsu Kaisen 0', 'Moneyball', 'I Want to Eat Your Pancreas', 'Pulp Fiction', 'Hot Fuzz', 'Reservoir Dogs', 'Mars Express', 'Nightcrawler', 'Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train', '12 Angry Men', 'Spider-Man', 'The Great Escape', 'A Silent Voice: The Movie', 'The Terminator', 'The Ugly Stepsister', 'Arrival', 'Sapta Sagaradaache Ello – Side A', 'Catch Me If You Can', 'Killers of the Flower Moon', 'Your Name.', 'The Town', 'Santosh', 'Rangasthalam', 'Talvar', 'Witness for the Prosecution', 'Terminator 2: Judgment Day', 'Udta Punjab', 'Carrie', "It's Never Over, Jeff Buckley", 'The Imitation Game', 'Shambhala', 'Drive', 'Fargo', 'The Martian', 'Ford v Ferrari', 'The Social Network', 'Bangalore Days', 'Prey', 'Edge of Tomorrow', 'The Year Without a Santa Claus', 'Heretic', 'Red Rooms', 'Laapataa Ladies', 'Ex Machina', 'No Way Out', 'Jurassic Park', 'Maybe Someday', '2001: A Space Odyssey', 'Back to the Future', 'The Fighter', 'Juror #2', 'Spotlight', 'Call Me by Your Name', 'Hundreds of Beavers', 'How to Train Your Dragon', 'Her', "Schindler's List", 'Mad Max 2: The Road Warrior', 'Midnight Express', 'Coraline', 'Young Frankenstein', 'Iron Man', 'Men in Black', 'Mission: Impossible - Dead Reckoning Part One', 'Baby Driver', 'Knives Out', 'Poor Things', 'John Wick: Chapter 4', 'Rocky', 'Licorice Pizza', 'Manchester by the Sea', 'Shaun of the Dead', 'Peaky Blinders: The Immortal Man', 'Up in the Air', 'Lagaan: Once Upon a Time in India', 'Apollo 13', 'Grave of the Fireflies', 'Mad Max: Fury Road', 'Kiss Me Deadly', 'Breathless', 'Guru', 'The Hurt Locker', '777 Charlie', 'Threads', 'Piku', 'WALL·E', 'The Taking of Pelham One Two Three', 'Cover-Up', 'Saving Private Ryan', 'Kill Bill: The Whole Bloody Affair', 'Kung Fu Hustle', 'Little Miss Sunshine', 'Mud', 'Warfare', 'Uncut Gems', 'Zero Dark Thirty', 'E.T. the Extra-Terrestrial', 'Apocalypse Now', 'A Beautiful Day in the Neighborhood', 'Twinless', 'Kaithi', 'Barbarian', 'Up', "Pan's Labyrinth", 'Palm Springs', 'The Perfect Neighbor', 'Network', 'Badlapur', 'Y Tu Mamá También', 'The Grand Budapest Hotel', 'Meet Me in St. Louis', 'Straume', 'Slumdog Millionaire', 'Snowpiercer', 'Titli', 'Spy', 'Little Women', 'The Lord of the Rings: The Return of the King', 'Anatomy of a Fall', 'Hidden Figures', 'Toy Story', 'Groundhog Day', 'Citizen Kane', 'Wuthering Heights', 'Wild Tales', 'The Witch', 'Sorry, Baby', 'L.A. Confidential', 'The Apartment', 'Arco', 'A Quiet Place', 'Source Code', 'Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan', 'Little Shop of Horrors', 'Amélie', 'K-Pop Demon Hunters', 'Airplane!', 'Creed', 'Midnight in Paris', 'Train to Busan', 'Hugo', 'Inside Out', 'Avengers: Endgame', 'City of God', 'Raat Akeli Hai', 'The Brutalist', 'Cure', 'Kill', 'Children of Men', 'The Zone of Interest', 'Raging Bull', 'Dìdi', 'Manhunter', 'All We Imagine as Light', 'Dungeons & Dragons: Honor Among Thieves', 'Sholay', 'Black Dog', 'The Worst Person in the World', 'This Is Spinal Tap', 'The Wailing', 'CODA', 'Silver Linings Playbook', 'Suzume', 'Furiosa: A Mad Max Saga', 'Die Hard', 'Come See Me in the Good Light', 'A Christmas Carol', 'Predator: Killer of Killers', 'The Northman', 'Psycho', 'Lost in Translation', 'Salaam Bombay!', 'The Good, the Bad and the Ugly', 'The Hunt', 'Three Billboards Outside Ebbing, Missouri', 'The Gift', 'Viduthalai: Part I', 'Spirited Away', 'Jab We Met', 'District 9', 'A Star Is Born', 'A Bronx Tale', 'After Hours', 'Promising Young Woman', 'The Avengers', 'Gravity', "Santa Claus Is Comin' to Town", 'The Philadelphia Story', 'Weathering with You', "Emmet Otter's Jug-Band Christmas", 'Sling Blade', 'The Station Agent', 'Ittefaq', 'Free Solo', 'In the Mood for Love', 'Lawrence of Arabia', 'Sunset Boulevard', "It's a Wonderful Life", 'The Peanut Butter Falcon', 'The Treasure of the Sierra Madre', 'Maqbool', 'Aftersun', 'Godzilla Minus One', 'Thiruchitrambalam', 'Special 26', 'Ran', 'Holiday Inn', 'The Fly', 'A Nice Indian Boy', 'Ullozhukku', 'October', 'Spider-Man: Far From Home', 'Casino Royale', 'Glass Onion: A Knives Out Mystery', 'Raiders of the Lost Ark', 'Million Dollar Baby', 'Jai Bhim', 'Vertigo', 'The Princess Bride', 'Spider-Man 2', 'The Shape of Water', 'The Banshees of Inisherin', "I'm Still Here", 'The Invisible Man', 'When Harry Met Sally...', 'Conclave', 'The Lord of the Rings: The Two Towers', 'Big Hero 6', 'Rudolph the Red-Nosed Reindeer', 'School of Rock', 'Boiling Point', 'Strange Darling', 'Harry Potter and the Deathly Hallows: Part 2', 'Good Time', '2018', 'BlackBerry', 'Mission: Impossible - Fallout', 'Escape from Mogadishu', 'Courageous Warriors Beauty from the Ashes', 'Downfall', 'Heojil kyolshim', 'The Suicide Squad', 'The Great Escaper', 'Kneecap', 'Ratatouille', 'The Cabin in the Woods', 'The Lego Movie', 'Bone Tomahawk', 'Fighting with My Family', 'Kahaani', 'The Godfather Part II', 'Ring', 'The Fugitive', 'Dr. No', 'Dogtooth', 'Lady Bird', 'Dil Chahta Hai', 'Volver', 'Coco', 'The Pianist', 'Sing Sing', "One Flew Over the Cuckoo's Nest", 'The Host', 'Finding Nemo', 'The White House Effect', 'From Russia with Love', 'Judgment at Nuremberg', 'Playtime', 'Kokuhô', 'Pink', 'Bridge of Spies', 'Sweet Smell of Success', 'Body Heat', 'Moothon', 'First Reformed', 'Eega', 'Thor: Ragnarok', 'Boogie Nights', 'Late Night with the Devil', 'Awe!', '100 METERS', 'Touch', 'Halloween', 'Hell or High Water', 'Downton Abbey: The Grand Finale', 'Aliens', 'How to Train Your Dragon: The Hidden World', 'The Ballad of Wallis Island', 'Shang-Chi and the Legend of the Ten Rings', 'Better Days', 'Society of the Snow', 'My Neighbor Totoro', 'The Wicker Man', 'A Quiet Place Part II', 'La haine', 'Almost Famous', 'The Commitments', 'Paterson', 'Willy Wonka & the Chocolate Factory', 'Togo', "I'm Your Man", 'No Other Land', 'Tangerine', 'El 47', 'North by Northwest', 'The Irishman', 'BlacKkKlansman', 'The Stringer: The Man Who Took the Photo', 'The Hunger Games: Catching Fire', "To All the Boys I've Loved Before", 'Article 15', 'Quiz Show', 'Midnight Run', 'Logan', 'Little Women', "It's the Great Pumpkin, Charlie Brown", 'Fantastic Mr. Fox', 'Harry Potter and the Prisoner of Azkaban', "Boys Don't Cry", 'Booksmart', 'Black Friday', 'Birdman or', 'Gone Baby Gone', 'Persepolis', 'Before Midnight', 'Edward Scissorhands', 'Kabhi Khushi Kabhie Gham', 'Pearl', 'Of Mice and Men', "Winter's Bone", 'Skyfall', 'Red Rocket', 'Blue Velvet', 'Another Round', 'The Man from Nowhere', 'Stalker', 'A Separation', 'Heathers', 'Akira', 'Monty Python and the Holy Grail', 'Dog Day Afternoon', "Selena y Los Dinos: A Family's Legacy", 'A Simple Plan', 'Fanaa', 'Ninja Scroll', 'Natsu e no tunnel, Sayonara no deguchi', 'Last Film Show', 'The Celebration', 'Amadeus', 'Suspiria', 'Neerja', 'Witness', 'Come and See', 'Looper', 'El Camino: A Breaking Bad Movie', '127 Hours', 'Escape from Alcatraz', 'A Fish Called Wanda', 'Adaptation.', 'The Vanishing', 'Air', 'Secret Superstar', 'The Holdovers', 'Puss in Boots: The Last Wish', 'Häxan', "Dane-ye anjir-e ma'abed", 'Thelma', 'Searching for Bobby Fischer', 'Good Luck to You, Leo Grande', 'War for the Planet of the Apes', 'The Mehta Boys', 'Phantom Thread', 'WarGames', 'Kes', 'The Conversation', 'Star Wars', 'Close Encounters of the Third Kind', 'A Christmas Carol', 'Rebecca', 'Dirty Pretty Things', 'Trainspotting', 'Columbus', 'Black Panther', 'Klaus', 'Jeremiah Johnson', 'Bacurau', '10 Cloverfield Lane', 'Once Upon a Time in the West', 'Le Comte de Monte-Cristo', 'Princess Mononoke', "Alice Doesn't Live Here Anymore", 'La Chimera', 'The Man in the Moon', 'Moonlight', 'Boyhood', 'The Third Man', 'Goldfinger', 'Speed', 'A Man Called Ove', 'Nomadland', 'The Favourite', 'Mary Poppins', 'The Great Dictator', 'Monsoon Wedding', 'Martha', 'Memoir of a Snail', 'High Fidelity', 'Blue Ruin', 'Michael Clayton', 'Dallas Buyers Club', 'Bob Trevino Likes It', 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 'Left-Handed Girl', 'Toy Story 2', 'Logan Lucky', 'Pather Panchali', 'How to Train Your Dragon 2', 'Fruitvale Station', 'Tokyo Godfathers', 'The Long Goodbye', 'Moon', '12 Years a Slave', 'Neighboring Sounds', 'West Side Story', 'A Fistful of Dollars', 'Grenfell: Uncovered', 'The Lives of Others', 'Star Wars: The Force Awakens', 'Inside Out 2', 'Tokyo Story', 'X-Men: Days of Future Past', 'House', 'Thappad', 'Deliverance', 'Minari', 'Nayattu', 'Toy Story 3', 'The White Tiger', 'sex, lies, and videotape', 'Mission: Impossible - Ghost Protocol', "All That's Left of You", 'Contempt', 'The Piano', 'October Sky', 'Ghost in the Shell', 'Seven Samurai', 'Chinatown', 'Fanny and Alexander', 'Kramer vs. Kramer', 'Dear Zachary: A Letter to a Son About His Father', 'Ghostbusters', 'For a Few Dollars More', 'The Blue Trail', 'Once Upon a Time in Anatolia', 'Le samouraï', 'Poorna', 'Lucky', 'Unforgiven', 'Beyond the Infinite Two Minutes', 'A Royal Affair', 'Masculin Féminin', 'The Leopard', 'Harakiri', 'Best in Show', 'Chicken Run', 'Tootsie', 'Aligarh', 'Tell Me Who I Am', 'Before Sunset', 'The Alabama Solution', 'Ocean with David Attenborough', 'Casablanca', 'Four Weddings and a Funeral', 'Paddington', 'Senna', 'That Thing You Do!', 'Lover, Stalker, Killer', 'The Blue Angel', 'Queen', 'Clerks', 'Mission: Impossible - Rogue Nation', 'Barton Fink', 'Jaws', 'Sardar Udham', 'Aattam', 'The French Connection', 'The General', 'Dating Amber', 'Rebel Without a Cause', 'One to One: John & Yoko', 'The Magnificent Seven', 'Out of Sight', 'Vishwaroopam', 'Persona', 'Room', 'An Honest Liar', 'Frankenstein', 'Newton', 'The Big Country', 'Rear Window', '12 Angry Men', 'The Spectacular Now', '8½', 'Captain America: Civil War', 'In the Heights', 'Evelyn', 'Cinema Paradiso', 'Moonrise Kingdom', 'Water', 'His Girl Friday', 'Conspiracy', 'Rushmore', 'Paddington 2', "All the President's Men", 'Three of Us', 'Searching', 'The Little Girl Who Lives Down the Lane', 'Disneyland Handcrafted', 'American Fiction', 'The Bridges of Madison County', 'The Day of the Jackal', 'The Night of the 12th', 'Amrum', 'Enchanted', 'The Florida Project', 'Fish Tank', 'King Richard', 'Maudie', 'Maaveeran', 'I, Tonya', 'Riders of Justice', 'Pictures of Ghosts', 'All of Us Strangers', 'Headhunters', 'In the Heat of the Night', 'Lessons of Darkness', 'EPiC: Elvis Presley in Concert', 'Riefenstahl', 'New Wave', 'Sound of Falling', 'Captain Phillips', 'The Man Who Would Be King', 'Paris, Texas', 'American Hustle', 'Nine Queens', 'Apollo 11', 'In the Loop', 'The Father', 'The Adventures of Baron Munchausen', "What's Eating Gilbert Grape", 'Beyond Utopia', 'Battle Royale', 'Kaathal - The Core', 'Duck, You Sucker', 'ONE SHOT with Ed Sheeran', 'Traffic', 'Brazil', 'Pinocchio', 'The Guard', 'Big', 'Malik', 'A Death in the Gunj', 'Monsters, Inc.', 'My Mom Jayne', 'Hard Truths', 'Places in the Heart', 'The Wild Bunch', 'In the Line of Fire', 'The Adventures of Priscilla, Queen of the Desert', 'Kapoor & Sons', 'The Man Who Feels No Pain', 'The Edge of Seventeen', 'Point Blank', 'Sairat', 'Girl in the Picture', "Souleymane's Story", 'The Wind That Shakes the Barley', 'The Jungle Book', 'The Kid', 'Hard Boiled', 'A Streetcar Named Desire', 'Gone with the Wind', 'The Empire Strikes Back', 'Eye in the Sky', 'Strangers on a Train', 'Double Indemnity', 'Mahanati', 'Charade', 'The Last Waltz', 'Porco Rosso', 'Encounters at the End of the World', 'Green Room', 'Run Lola Run', 'Guardians of the Galaxy', 'Marty', 'Deaf President Now!', 'Forbidden Planet', 'Isle of Dogs', 'The Battle of Algiers', 'The Seventh Seal', "Hearts of Darkness: A Filmmaker's Apocalypse", "Are You There God? It's Me, Margaret.", 'Ponyo', 'This Is England', 'American Graffiti', 'The Gold Rush', 'Cool Hand Luke', 'Wallace & Gromit: Vengeance Most Fowl', 'M', 'Arthur Christmas', 'The Night of the Hunter', 'My Life as a Zucchini', 'Manhattan', 'The Fabelmans', 'What Ever Happened to Baby Jane?', 'About a Boy', 'Life of Brian', 'Shakespeare in Love', 'Cabaret', 'Shahid', 'Love & Mercy', 'Angst', 'Dracula', 'Shiva Baby', 'Full Metal Jacket', 'Elite Squad: The Enemy Within', 'In the Bedroom', 'Paper Moon', 'Carol', 'The Elephant Man', 'Leaving Las Vegas', 'The Nightmare Before Christmas', 'How to Make Millions Before Grandma Dies', 'Shaun the Sheep Movie', 'The 400 Blows', 'Deep Red', 'The Long Good Friday', 'Manhattan Murder Mystery', 'Duel', 'Rashomon', 'Shazam!', 'The Iron Giant', 'Only the Animals', 'Sideways', 'Capernaum', 'True Romance', 'Moana', 'The Muppets', 'My Undesirable Friends: Part I - Last Air in Moscow', 'Till', 'Evil Does Not Exist', 'Castle in the Sky', 'Court', 'The Wrecking Crew', 'Belén', 'All That Heaven Allows', 'The Miracle Worker', 'The Bourne Ultimatum', 'One Life', 'Captain America: The Winter Soldier', 'Take Shelter', 'Moonage Daydream', 'Modern Times', "The Teachers' Lounge", 'Toni Erdmann', 'Red River', 'Sleeping Beauty', 'Mulk', 'Gods and Monsters', 'Amores Perros', 'The Great Beauty', 'Vampire humaniste cherche suicidaire consentant', 'Mountain Queen: The Summits of Lhakpa Sherpa', 'What We Do in the Shadows', 'The Wizard of Oz', 'The Great Indian Kitchen', 'Marriage Story', 'The Act of Killing', 'Becoming', 'Badhaai Ho', 'Stiller & Meara: Nothing Is Lost', 'High and Low', 'The Secret of Roan Inish', 'The Hustler', 'Miracle on 34th Street', 'Paths of Glory', 'Old Henry', 'Music by John Williams', 'Dead Man Walking', 'Planes, Trains and Automobiles', 'The Summit of the Gods', 'Eastern Promises', 'Hunt for the Wilderpeople', 'The Disciple', 'The Tale of Silyan', 'Cold War', 'Dinner in America', 'The Insider', "National Lampoon's Vacation", 'West Side Story', 'Days of Heaven', 'The Wrestler', 'Gargi', 'A Real Pain', 'City Lights', 'The Red Turtle', 'The Odd Couple', 'Rio Bravo', 'Jaws @ 50: The Definitive Inside Story', 'Pumping Iron', 'Selma', 'Burning', 'Gulmohar', 'Out of My Mind', 'The Big Sick', 'One Cut of the Dead', 'The Eight Mountains'] ['2025', '2025', '2025', '2025', '2025', '2025', '2026', '2026', '2025', '2025', '2018', '2025', '2026', '2026', '2025', '2025', '2016', '2018', '2025', '2016', '2004', '2000', '2019', '1962', '2025', '2003', '2025', '1968', '2024', '1991', '2007', '1972', '2016', '2012', '1927', '2021', '2001', '2025', '1998', '2022', '2019', '1997', '2011', '2022', '2004', '2010', '2025', '2015', '2023', '2016', '2026', '2006', '2019', '2007', '2007', '2015', '2018', '2024', '2017', '1995', '1990', '2023', '2022', '2017', '2006', '2007', '2013', '2022', '2002', '2025', '1945', '2025', '2014', '2024', '2007', '2010', '2023', '2018', '2008', '2024', '2018', '2023', '2015', '2021', '2011', '2018', '1994', '2007', '1992', '2023', '2014', '2020', '1957', '2002', '1963', '2016', '1984', '2025', '2016', '2023', '2002', '2023', '2016', '2010', '2024', '2018', '2015', '1958', '1991', '2016', '1976', '2025', '2014', '2024', '2011', '1996', '2015', '2019', '2010', '2014', '2022', '2014', '1974', '2024', '2023', '2024', '2015', '1987', '1993', '2022', '1968', '1985', '2010', '2024', '2015', '2017', '2024', '2010', '2013', '1993', '1981', '1978', '2009', '1974', '2008', '1997', '2023', '2017', '2019', '2023', '2023', '1976', '2021', '2016', '2004', '2026', '2009', '2001', '1995', '1988', '2015', '1955', '1960', '2007', '2008', '2022', '1985', '2015', '2008', '1974', '2025', '1998', '2011', '2004', '2006', '2013', '2025', '2019', '2012', '1982', '1979', '2019', '2025', '2019', '2022', '2009', '2006', '2020', '2025', '1976', '2015', '2001', '2014', '1944', '2024', '2008', '2013', '2015', '2015', '2019', '2003', '2023', '2016', '1995', '1993', '1941', '1939', '2014', '2015', '2025', '1997', '1960', '2025', '2018', '2011', '2006', '1986', '2001', '2025', '1980', '2015', '2011', '2016', '2011', '2015', '2019', '2002', '2020', '2024', '1997', '2024', '2006', '2023', '1980', '2024', '1986', '2024', '2023', '1975', '2024', '2021', '1984', '2016', '2021', '2012', '2022', '2024', '1988', '2025', '1984', '2025', '2022', '1960', '2003', '1988', '1966', '2012', '2017', '2015', '2023', '2001', '2007', '2009', '2018', '1993', '1985', '2020', '2012', '2013', '1970', '1940', '2019', '1977', '1996', '2003', '2017', '2018', '2000', '1962', '1950', '1946', '2019', '1948', '2003', '2022', '2023', '2022', '2013', '1985', '1942', '1986', '2025', '2024', '2018', '2019', '2006', '2022', '1981', '2004', '2021', '1958', '1987', '2004', '2017', '2022', '2024', '2020', '1989', '2024', '2002', '2014', '1964', '2003', '2021', '2024', '2011', '2017', '2023', '2023', '2018', '2021', '2022', '2004', '2022', '2021', '2023', '2024', '2007', '2012', '2014', '2015', '2019', '2012', '1974', '1998', '1993', '1962', '2009', '2017', '2001', '2006', '2017', '2002', '2024', '1975', '2006', '2003', '2024', '1963', '1961', '1967', '2025', '2016', '2015', '1957', '1981', '2019', '2018', '2012', '2017', '1997', '2024', '2018', '2025', '2024', '1978', '2016', '2025', '1986', '2019', '2025', '2021', '2019', '2023', '1988', '1973', '2021', '1995', '2000', '1991', '2016', '1971', '2019', '2021', '2024', '2015', '2024', '1959', '2019', '2018', '2025', '2013', '2018', '2019', '1994', '1988', '2017', '1994', '1966', '2009', '2004', '1999', '2019', '2004', '2014', '2007', '2007', '2013', '1990', '2001', '2022', '1992', '2010', '2012', '2021', '1986', '2020', '2010', '1979', '2011', '1989', '1988', '1975', '1975', '2025', '1998', '2006', '1993', '2022', '2022', '1998', '1984', '1977', '2016', '1985', '1985', '2012', '2019', '2010', '1979', '1988', '2002', '1988', '2023', '2017', '2023', '2022', '1922', '2024', '2024', '1993', '2022', '2017', '2024', '2017', '1983', '1970', '1974', '1977', '1977', '1938', '1940', '2002', '1996', '2017', '2018', '2019', '1972', '2019', '2016', '1968', '2024', '1997', '1974', '2023', '1991', '2016', '2014', '1949', '1964', '1994', '2015', '2020', '2018', '1964', '1940', '2001', '2024', '2024', '2000', '2014', '2007', '2013', '2025', '1964', '2025', '1999', '2017', '1955', '2014', '2013', '2003', '1973', '2009', '2013', '2012', '1961', '1964', '2025', '2006', '2015', '2024', '1953', '2014', '1977', '2020', '1972', '2021', '2021', '2010', '2021', '1989', '2011', '2025', '1963', '1993', '1999', '1995', '1954', '1974', '1982', '1979', '2008', '1984', '1965', '2025', '2011', '1967', '2017', '2017', '1992', '2020', '2012', '1966', '1963', '1962', '2000', '2000', '1982', '2016', '2019', '2004', '2025', '2025'

In [36]:
df = pd.DataFrame({
    "title": titles,
    "year": years,
    'genre':genres_list,
    "runtime":runtime_list,
    "imdb_rating": imdb_ratings,
    "country":country_list,
    "director":directors_list,
    "no._of_reviews": imdb_reviews_list,
    "url": urls,
    'actor':main_actors
})

df

,title,year,genre,runtime,imdb_rating,country,director,no._of_reviews,url,actor
0,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025,Animation,2h 35min,8.4,Japan,Haruo Sotozaki,66k,https://www.justwatch.com/in/movie/demon-slaye...,Natsuki Hanae
1,One Battle After Another,2025,Mystery & Thriller,2h 41min,7.7,United States,Paul Thomas Anderson,343k,https://www.justwatch.com/in/movie/the-battle-...,Leonardo DiCaprio
2,Marty Supreme,2025,Drama,2h 29min,7.8,Finland,Josh Safdie,120k,https://www.justwatch.com/in/movie/marty-supreme,Timothée Chalamet
3,Zootopia 2,2025,Animation,1h 48min,7.4,Canada,Jared Bush,90k,https://www.justwatch.com/in/movie/zootopia-2,Byron Howard
4,Ne Zha 2,2025,Fantasy,2h 24min,7.9,China,Yang Yu,23k,https://www.justwatch.com/in/movie/ne-zha-2,Lu Yanting
...,...,...,...,...,...,...,...,...,...,...
795,Gulmohar,2023,Drama,2h 11min,7.6,India,Rahul V. Chittella,5.9k,https://www.justwatch.com/in/movie/gulmohar-2023,Sharmila Tagore
796,Out of My Mind,2024,Drama,1h 47min,7.4,United States,Amber Sealey,3.3k,https://www.justwatch.com/in/movie/out-of-my-mind,Phoebe-Rae Taylor
797,The Big Sick,2017,Comedy,2h 0min,7.5,United States,Michael Showalter,150k,https://www.justwatch.com/in/movie/the-big-sick,Kumail Nanjiani
798,One Cut of the Dead,2017,Comedy,1h 36min,7.6,Japan,Shinichiro Ueda,35k,https://www.justwatch.com/in/movie/one-cut-of-...,Takayuki Hamatsu
799,The Eight Mountains,2022,Drama,2h 27min,7.7,United Kingdom,Felix van Groeningen,19k,https://www.justwatch.com/in/movie/the-eight-m...,Charlotte Vandermeersch

In [27]:
#change runtime hour and minute into only minutes 
def runtime_to_minutes(text):
    if text is None:
        return None
    
    hours = re.search(r'(\d+)h', text)
    mins = re.search(r'(\d+)min', text)
    
    h = int(hours.group(1)) if hours else 0
    m = int(mins.group(1)) if mins else 0
    
    return h * 60 + m

In [38]:
df['runtime'] = df['runtime'].apply(runtime_to_minutes)

In [39]:
df.rename(columns={'runtime':'runtime_in_min'},inplace=True)

In [40]:
df.head()

,title,year,genre,runtime_in_min,imdb_rating,country,director,no._of_reviews,url,actor
0,Demon Slayer: Kimetsu no Yaiba Infinity Castle,2025,Animation,155,8.4,Japan,Haruo Sotozaki,66k,https://www.justwatch.com/in/movie/demon-slaye...,Natsuki Hanae
1,One Battle After Another,2025,Mystery & Thriller,161,7.7,United States,Paul Thomas Anderson,343k,https://www.justwatch.com/in/movie/the-battle-...,Leonardo DiCaprio
2,Marty Supreme,2025,Drama,149,7.8,Finland,Josh Safdie,120k,https://www.justwatch.com/in/movie/marty-supreme,Timothée Chalamet
3,Zootopia 2,2025,Animation,108,7.4,Canada,Jared Bush,90k,https://www.justwatch.com/in/movie/zootopia-2,Byron Howard
4,Ne Zha 2,2025,Fantasy,144,7.9,China,Yang Yu,23k,https://www.justwatch.com/in/movie/ne-zha-2,Lu Yanting

In [42]:
#convert reviews no. from k or m to number
def convert_reviews(x):
    if isinstance(x, str):
        x = x.lower()
        if "k" in x:
            return float(x.replace("k","")) * 1000
        elif "m" in x:
            return float(x.replace("m","")) * 1000000
        else:
            return float(x)
    return x

df["no._of_reviews"] = df["no._of_reviews"].apply(convert_reviews)

In [45]:
df.sample(10)

,title,year,genre,runtime_in_min,imdb_rating,country,director,no._of_reviews,url,actor
341,Coco,2017,Animation,109,8.4,United States,Lee Unkrich,698000.0,https://www.justwatch.com/in/movie/coco,Anthony Gonzalez
325,The Great Escaper,2023,History,96,7.0,Sweden,Oliver Parker,10000.0,https://www.justwatch.com/in/movie/the-great-e...,Michael Caine
575,Vishwaroopam,2013,Mystery & Thriller,147,7.9,India,Kamal Haasan,41000.0,https://www.justwatch.com/in/movie/vishwaroopam,Kamal Haasan
626,American Hustle,2013,Crime,138,7.2,United States,David O. Russell,517000.0,https://www.justwatch.com/in/movie/american-hu...,Christian Bale
470,Once Upon a Time in the West,1968,Drama,166,8.5,Italy,Sergio Leone,382000.0,https://www.justwatch.com/in/movie/once-upon-a...,Claudia Cardinale
88,Reservoir Dogs,1992,Mystery & Thriller,99,8.3,United States,Quentin Tarantino,1000000.0,https://www.justwatch.com/in/movie/reservoir-dogs,Harvey Keitel
715,How to Make Millions Before Grandma Dies,2024,Drama,126,7.9,Thailand,Pat Boonnitipat,21000.0,https://www.justwatch.com/in/movie/how-to-make...,Putthipong Assaratanakul
531,Kramer vs. Kramer,1979,Drama,105,7.8,United States,Robert Benton,165000.0,https://www.justwatch.com/in/movie/kramer-vs-k...,Dustin Hoffman
641,The Guard,2011,Action & Adventure,96,7.3,Ireland,John Michael McDonagh,101000.0,https://www.justwatch.com/in/movie/the-guard,Brendan Gleeson
188,The Perfect Neighbor,2025,Crime,97,7.1,United States,Geeta Gandbhir,27000.0,https://www.justwatch.com/in/movie/the-perfect...,None

In [46]:
df.to_csv('top_800_movies_based_on_imdb.csv',index=False)